### ISSUE TITLE
Blockdrops bug

### ISSUE THREAD

**Issue by LimeTheOn** [RayzoRayy/RaysDongles#7] opened 2019-08-15 12:30 UTC
Describe the bug:
Mined blocks don't drop as an item.

To Reproduce:
Steps to reproduce the behaviour:
Try mining lets say a dirt block with later specified versions of mc-forge-sd.

Expected behaviour:
Most mined blocks drop as an item.

Forge Version- 28.0.45
Minecraft Version- 1.14.4
Slurpie's Dongles Version- 2.0.1

Tested with tools in hand, makes no difference.
Tested on forge 28.0.46 too, same thing happens.

**Comment by LimeTheOn** [comment] 2019-08-15 12:36
2.0.0 works just fine so whatever happened between the two version will be your culprit :)

**Comment by RayzoRayy** [comment] 2019-08-15 12:40
Thanks for the report. I'll get a fix out asap

**Comment by RayzoRayy** [comment] 2019-08-15 14:39
Issue is fixed. 2.0.2 will be out shortly. Thanks for the report

**Comment by RayzoRayy** [comment] 2019-08-15 15:41
Seems the issue is not fixed on latest version. -_- I will look into it again.

**Comment by RayzoRayy** [comment] 2019-08-15 15:43
Nevermind.. Twitch launcher just borked and downloaded verison 2.0.1 when I thought it was 2.0.2 even tho I archived 2.0.1 .-_- Issue is fixed as intended in 2.0.2

**Closed as completed by RayzoRayy** 2019-08-15 15:43 UTC
Labels: Fixed

**Comment by LimeTheOn** [comment] 2019-08-16 09:26
Its been doing that for a while now, I've actually had to reinstall twitch this morning it was soooo bad.
Not sure if it helps that much but I get complaint rights if nothing is fixing its behaviour, right? :D
