### ISSUE TITLE
{Reviewed} Game failed to load mods. 

### ISSUE THREAD

**Issue by Gbergz** [RayzoRayy/RaysDongles#3] opened 2019-02-25 17:02 UTC
**To Reproduce**
1. Start the game with the mod
2. Wait a little.
3. Game "crashes" or just failed to load mods.

**Expected behavior**
The game loading up as normal.

**Screenshots**
Screenshot: [Gyazo](https://gyazo.com/6c620604b0ff9165b984bdee1b3c0377)

**Logs**
Logs: [Pastebin](https://pastebin.com/2pahv5GD)

**Please complete the following information**
Forge Version- 1.13.2 - 25.0.54
Minecraft Version- 1.13.2
Slurpie's Dongles Version- 1.13.2 - 2.19.4

**Please list all mod(s) AND version(s) here that you are currently using with my mod**
[Gyazo Link All mods](https://i.gyazo.com/97b0678c75db1dbbbb7bb924fd691d7f.png)

**Additional context**
None.

EDIT: Game works and loads as normal with the version "2.19.2" !

**Comment by RayzoRayy** [comment] 2019-02-25 17:21
I shall take a look into why 2.19.3 and .4 aren't loading. I see what the issue is, but it is the same on 2.19.2 so I'm not sure why it wouldn't work on 
3 or 4. I shall take a look at this later tonight when I am home. Thank you for the report.

**Comment by RayzoRayy** [comment] 2019-02-26 05:23
Not quite sure what is causing this issue as the mod works fine in Intelijay, but does not seem to work once the mod is actually built into a Jar file. I'll look more into this tomorrow and figure out why it is crashing once being built, again thank you for the report.

**Comment by RayzoRayy** [comment] 2019-02-26 18:05
This issue has been fixed in 2.19.5, however it MAY require that a new world be made. You can try loading the old world however if it crashes then you will need a new world.

**Closed as completed** 2019-02-26 18:05 UTC
Labels: Fixed
